import { MigrationInterface, QueryRunner } from 'typeorm';

export class CheckDatabaseFoundation1710000000000 implements MigrationInterface {
  name = 'CheckDatabaseFoundation1710000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "schema_migration_checks" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "label" varchar(64) NOT NULL UNIQUE,
        "created_at" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      INSERT INTO "schema_migration_checks" ("label")
      VALUES ('story-002-foundation')
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "schema_migration_checks"');
  }
}
